spring:
  kafka:
    consumer:
      bootstrap-servers: 172.30.167.109:9092
      properties:
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="ycyin" password="ycyin@123!";
    producer:
      bootstrap-servers: 172.30.167.109:9092
      properties:
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="ycyin" password="ycyin@123!";